apiVersion: apps/v1
kind: Deployment
metadata:
  name: naacp-gcs-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: naacp-gcs-3
  template:
    metadata:
      labels:
        app: naacp-gcs-3
    spec:
      containers:
      - name: naacp-gcs-container
        image: us-east1-docker.pkg.dev/special-michelle/naacp/test_gcs_3
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /code/app/keys/naacp-ser-acc.json