apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: special-michelle # kpt-set: ${gcloud.core.project}
commonAnnotations:
  # Annotation required by anthoscli
  gke.io/cluster: "bootstrap://"
resources:
- iam.yaml
